"""
SpeechStudio Engine - Audio Manager
====================================

Engine Specification, section 10:
    "AudioManager is responsible for: Playback, Saving WAV, Appending
     silence, Volume normalization, Waveform generation, Audio metadata.
     The AudioManager never communicates directly with the model."

AI Development Rules, section 5:
    "AudioManager - handles audio only"

Generation Engine Specification, section 9 (Audio Post Processing):
    "The engine may optionally append silence after generation.
     Purpose: Prevent abrupt audio ending.
     Implementation: Append zero samples. Duration configurable."

Generation Engine Specification, section 10 (Output Naming):
    "Default naming: yyyyMMdd_HHmmss.wav"

Generation Engine Specification, section 11 (Output Directory):
    "Default: outputs/. The engine shall create the directory if missing."

Single responsibility: handle audio buffers (save, pad, normalise, play).
Never loads the model, never builds prompts, never manages voices.
"""

from __future__ import annotations
import os
import time
import wave
import struct
import threading
from datetime import datetime
from typing import Optional, Tuple, Callable

from engine.logger import get_logger
from engine.errors import OutputWriteFailed

logger = get_logger("audio_manager")


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
# Higgs Audio V3 outputs 24 kHz mono float32.
HIGGS_SAMPLE_RATE = 24000


class AudioManager:
    """Handles audio buffers, file I/O, and playback.

    The AudioManager owns playback buffers and saved audio files (Engine
    Specification section 20: Memory Ownership). It never communicates
    with the model.

    Audio data is exchanged as NumPy float32 arrays in the range [-1.0, 1.0].
    """

    def __init__(self, outputs_dir: str):
        self._outputs_dir = outputs_dir
        os.makedirs(outputs_dir, exist_ok=True)
        self._playback_lock = threading.RLock()
        self._current_playback: Optional[_PlaybackHandle] = None
        self._position_callback: Optional[Callable[[float, float], None]] = None
        self._finished_callback: Optional[Callable[[], None]] = None
        # Master volume (linear gain 0.0 - 1.0). Applied to every new
        # playback; live-adjustable via set_volume() during playback.
        self._volume: float = 1.0

    @property
    def outputs_dir(self) -> str:
        """The directory generated WAV files are written to (P3.27B:
        exposed so the UI can allocate versioned part filenames with a
        disk-guard against overwriting previous versions)."""
        return self._outputs_dir

    # ------------------------------------------------------------------
    # Saving
    # ------------------------------------------------------------------
    def save_wav(self, samples, sample_rate: int = HIGGS_SAMPLE_RATE,
                 filename: Optional[str] = None) -> str:
        """Save a float32 waveform to a WAV file.

        Args:
            samples: a float32 array (1-D mono) with values in [-1.0, 1.0].
            sample_rate: sample rate in Hz (default 24000 for Higgs Audio V3).
            filename: optional filename; if None, auto-generated by timestamp.

        Returns:
            The relative path to the saved WAV file (relative to app root).

        Raises:
            OutputWriteFailed: if the file cannot be written.
        """
        if filename is None:
            # P3.25 (audit SS-M05): second-resolution timestamps made two
            # same-second generations silently overwrite each other's
            # audio. Auto-generated names now carry milliseconds and are
            # de-duplicated against existing files.
            base = datetime.now()
            filename = base.strftime("%Y%m%d_%H%M%S") + ".wav"
            full = os.path.join(self._outputs_dir, filename)
            if os.path.exists(full):
                filename = "{0}_{1}.wav".format(
                    base.strftime("%Y%m%d_%H%M%S"), base.strftime("%f")[:3])
                full = os.path.join(self._outputs_dir, filename)
                counter = 1
                while os.path.exists(full):
                    filename = "{0}_{1}_{2}.wav".format(
                        base.strftime("%Y%m%d_%H%M%S"),
                        base.strftime("%f")[:3], counter)
                    full = os.path.join(self._outputs_dir, filename)
                    counter += 1
        else:
            # P3.28 (§19 / design record Rec 21 — defect D-8): explicit
            # filenames are contained HARD within the outputs directory.
            # Basename + separator-stripping blocks "../" traversal,
            # absolute paths, UNC escapes and drive-path injection; the
            # resolved path is containment-checked as defence in depth.
            safe = os.path.basename(str(filename).replace("\\", "/"))
            for ch in ("/", "\\", "\x00"):
                safe = safe.replace(ch, "_")
            safe = safe.strip()
            if not safe or set(safe) <= {".", " "} or safe in (".", ".."):
                raise OutputWriteFailed(
                    "Unsafe output filename rejected: {0!r}".format(filename))
            filename = safe
            full = os.path.join(self._outputs_dir, filename)
            # Defence in depth: the resolved path must stay inside the
            # outputs directory (never follows traversal/absolute forms).
            try:
                out_abs = os.path.realpath(self._outputs_dir)
                full_abs = os.path.realpath(full)
                if os.path.commonpath([out_abs, full_abs]) != out_abs:
                    raise OutputWriteFailed(
                        "Output filename escapes the outputs directory: "
                        "{0!r}".format(filename))
            except ValueError as exc:
                raise OutputWriteFailed(
                    "Unsafe output filename: {0!r} ({1})".format(
                        filename, exc)) from exc
            # P3.28 (§19): NEVER silently overwrite an existing generated
            # file. The version allocators upstream (output_guard /
            # audio_provenance) guarantee fresh names; reaching this point
            # means an unversioned collision — fail loudly so the user
            # can choose a different name.
            if os.path.exists(full):
                raise OutputWriteFailed(
                    "Output file already exists — not overwriting: {0}. "
                    "Choose a different filename (the previous generated "
                    "audio is preserved).".format(filename))

        full_path = os.path.join(self._outputs_dir, filename)
        try:
            self._write_wav(full_path, samples, sample_rate)
            rel_path = os.path.relpath(full_path, self._get_app_root())
            logger.info("Audio saved: %s (%d samples, %d Hz)",
                        rel_path, len(samples), sample_rate)
            return rel_path
        except OSError as exc:
            raise OutputWriteFailed(
                "Could not write WAV file: {0}".format(exc),
            ) from exc

    def _write_wav(self, path: str, samples, sample_rate: int) -> None:
        """Write a float32 array to a 32-bit float WAV file.

        Uses soundfile (primary) or the wave module with header patching
        (fallback) to write 32-bit float WAV, matching the original Higgs
        Audio V3 prototype's torchaudio.save() output format.

        32-bit float WAV preserves the exact model output without clipping
        or quantization noise.
        """
        import numpy as np

        arr = np.asarray(samples, dtype=np.float32)
        if arr.ndim > 1:
            arr = arr.flatten()

        # Primary: use soundfile (writes 32-bit float WAV directly)
        try:
            import soundfile as sf
            sf.write(path, arr, sample_rate, subtype='FLOAT')
            return
        except ImportError:
            pass

        # Fallback: write 32-bit float WAV using wave module + header patch
        import struct
        raw_bytes = arr.tobytes()
        with wave.open(path, "wb") as wav:
            wav.setnchannels(1)
            wav.setsampwidth(4)  # 32-bit
            wav.setframerate(sample_rate)
            wav.writeframes(raw_bytes)
        # Patch WAV header: format code 3 = IEEE float (wave module writes 1=PCM)
        with open(path, "r+b") as f:
            f.seek(20)  # AudioFormat field in fmt chunk
            f.write(struct.pack('<H', 3))

    # ------------------------------------------------------------------
    # Post-processing
    # ------------------------------------------------------------------
    def append_silence(self, samples, duration_seconds: float,
                       sample_rate: int = HIGGS_SAMPLE_RATE):
        """Append zero samples to the end of a waveform.

        Generation Engine Specification section 9: "Append zero samples.
        Duration configurable."

        Returns a new array; the original is not modified.
        """
        if duration_seconds <= 0:
            return samples
        import numpy as np
        num_silence = int(duration_seconds * sample_rate)
        silence = np.zeros(num_silence, dtype=np.float32)
        return np.concatenate([np.asarray(samples, dtype=np.float32), silence])

    def normalize_volume(self, samples):
        """Normalise the peak amplitude to 1.0 (if non-zero).

        Returns a new array; the original is not modified.
        """
        import numpy as np
        arr = np.asarray(samples, dtype=np.float32)
        peak = np.max(np.abs(arr))
        if peak > 0:
            return arr / peak
        return arr

    def normalize_to_lufs(self, samples, target_lufs: float = -18.0):
        """Normalize audio to a target loudness level in LUFS.

        Simplified loudness normalization (RMS-based approximation).
        Uses soft limiting (tanh) to prevent hard clipping.
        """
        import numpy as np
        arr = np.asarray(samples, dtype=np.float32)
        if len(arr) == 0:
            return arr
        rms = float(np.sqrt(np.mean(arr ** 2)))
        if rms < 1e-8:
            return arr
        rms_dbfs = 20.0 * np.log10(rms)
        current_lufs = rms_dbfs - 0.691
        gain_db = target_lufs - current_lufs
        gain_linear = 10.0 ** (gain_db / 20.0)
        normalized = arr * gain_linear
        # Soft limit peaks above 0.99
        overshoot_mask = np.abs(normalized) > 0.99
        if np.any(overshoot_mask):
            normalized[overshoot_mask] = np.sign(normalized[overshoot_mask]) * (
                0.99 + 0.01 * np.tanh(
                    (np.abs(normalized[overshoot_mask]) - 0.99) * 10))
        return normalized.astype(np.float32)

    def analyze_audio(self, samples, sample_rate: int) -> dict:
        """Analyze a waveform and return audio quality metrics."""
        import numpy as np
        arr = np.asarray(samples, dtype=np.float32)
        if arr.ndim > 1:
            arr = arr.flatten()
        peak = float(np.max(np.abs(arr))) if len(arr) > 0 else 0.0
        peak_dbfs = 20.0 * np.log10(peak) if peak > 0 else -float('inf')
        rms = float(np.sqrt(np.mean(arr ** 2))) if len(arr) > 0 else 0.0
        rms_dbfs = 20.0 * np.log10(rms) if rms > 0 else -float('inf')
        loudness_lufs = rms_dbfs - 0.691 if rms_dbfs > -70 else -70.0
        duration = len(arr) / float(sample_rate) if sample_rate > 0 else 0.0
        clipped_samples = int(np.sum(np.abs(arr) >= 0.99))
        clipping_detected = clipped_samples > 0
        clip_percent = (clipped_samples / len(arr) * 100) if len(arr) > 0 else 0.0
        dc_offset = float(np.mean(arr)) if len(arr) > 0 else 0.0
        return {
            'sample_rate': sample_rate, 'channels': 1,
            'bit_depth': '32-bit float', 'file_format': 'WAV (IEEE Float)',
            'peak_dbfs': round(peak_dbfs, 1), 'rms_dbfs': round(rms_dbfs, 1),
            'loudness_lufs': round(loudness_lufs, 1), 'duration': round(duration, 2),
            'clipping_detected': clipping_detected, 'clip_percent': round(clip_percent, 2),
            'dc_offset': round(dc_offset, 6),
        }

    # ------------------------------------------------------------------
    # Reading (for playback and waveform display)
    # ------------------------------------------------------------------
    def load_wav(self, path: str) -> Tuple:
        """Load a WAV file and return (float32_samples, sample_rate).

        Uses soundfile (primary) or wave module with float fallback.
        """
        import numpy as np

        full_path = path
        if not os.path.isabs(path):
            full_path = os.path.join(self._get_app_root(), path)
        if not os.path.isfile(full_path):
            raise FileNotFoundError("Audio file not found: {0}".format(path))

        # Primary: use soundfile (handles all WAV subtypes)
        try:
            import soundfile as sf
            data, sample_rate = sf.read(full_path, dtype='float32')
            if data.ndim > 1:
                data = data.mean(axis=1)
            return data, sample_rate
        except ImportError:
            pass

        # Fallback: use wave module
        import struct

        try:
            with wave.open(full_path, "rb") as wav:
                sample_rate = wav.getframerate()
                n_channels = wav.getnchannels()
                sampwidth = wav.getsampwidth()
                frames = wav.readframes(wav.getnframes())
        except Exception as wav_error:
            if "unknown format" in str(wav_error):
                return self._read_float_wav_manual(full_path)
            raise

        if sampwidth == 2:
            int_data = np.frombuffer(frames, dtype="<i2")
            float_data = int_data.astype(np.float32) / 32768.0
        elif sampwidth == 4:
            float_data = np.frombuffer(frames, dtype="<f4")
        else:
            raise ValueError("Unsupported sample width: {0}".format(sampwidth))

        if n_channels > 1:
            float_data = float_data.reshape(-1, n_channels).mean(axis=1)

        return float_data, sample_rate

    def _read_float_wav_manual(self, path: str) -> Tuple:
        """Manually read a 32-bit IEEE float WAV file."""
        import numpy as np
        import struct

        with open(path, "rb") as f:
            data = f.read()

        if data[:4] != b"RIFF" or data[8:12] != b"WAVE":
            raise ValueError("Not a valid WAV file")

        pos = 12
        sample_rate = 24000
        n_channels = 1
        while pos < len(data) - 8:
            chunk_id = data[pos:pos+4]
            chunk_size = struct.unpack("<I", data[pos+4:pos+8])[0]
            if chunk_id == b"fmt ":
                n_channels = struct.unpack("<H", data[pos+10:pos+12])[0]
                sample_rate = struct.unpack("<I", data[pos+12:pos+16])[0]
            elif chunk_id == b"data":
                raw_audio = data[pos+8:pos+8+chunk_size]
                float_data = np.frombuffer(raw_audio, dtype="<f4")
                if n_channels > 1:
                    float_data = float_data.reshape(-1, n_channels).mean(axis=1)
                return float_data, sample_rate
            pos += 8 + chunk_size
            if chunk_size % 2 == 1:
                pos += 1

        raise ValueError("Could not find data chunk in WAV file")

    def get_duration(self, samples, sample_rate: int = HIGGS_SAMPLE_RATE) -> float:
        """Return the duration in seconds of a waveform."""
        return len(samples) / float(sample_rate) if sample_rate > 0 else 0.0

    # ------------------------------------------------------------------
    # Concatenation (Long Narration)
    # ------------------------------------------------------------------
    def concatenate(self, file_paths: list, output_path: str,
                    crossfade_ms: int = 100) -> str:
        """Concatenate multiple WAV files into one.

        Args:
            file_paths: list of WAV file paths to concatenate (in order).
            output_path: destination file path.
            crossfade_ms: crossfade duration in milliseconds between parts.

        Returns:
            Path to the concatenated WAV file.
        """
        import numpy as np

        if not file_paths:
            return ""

        all_samples = []
        sample_rate = HIGGS_SAMPLE_RATE
        crossfade_samples = int(crossfade_ms * sample_rate / 1000)

        for i, path in enumerate(file_paths):
            try:
                samples, sr = self.load_wav(path)
                if i == 0:
                    sample_rate = sr

                # Ensure mono
                if samples.ndim > 1:
                    samples = samples.flatten()

                # Resample if needed (simple — just use as-is if same rate)
                if sr != sample_rate:
                    logger.warning("Sample rate mismatch in part %d: %d vs %d",
                                   i, sr, sample_rate)

                if i > 0 and crossfade_samples > 0 and len(all_samples) > 0:
                    # Apply simple crossfade: linear fade out last part of
                    # previous, fade in first part of current
                    fade_len = min(crossfade_samples,
                                   len(all_samples[-1]), len(samples))
                    if fade_len > 0:
                        fade_out = np.linspace(1.0, 0.0, fade_len)
                        fade_in = np.linspace(0.0, 1.0, fade_len)
                        all_samples[-1][-fade_len:] *= fade_out
                        samples[:fade_len] *= fade_in

                all_samples.append(samples.astype(np.float32))
            except Exception as exc:
                logger.error("Failed to load part %d for concat: %s", i, exc)

        if not all_samples:
            return ""

        combined = np.concatenate(all_samples)

        # Save
        self._write_wav(output_path, combined, sample_rate)
        rel_path = os.path.relpath(output_path, self._get_app_root())
        logger.info("Concatenated %d parts into %s (%.1fs)",
                    len(file_paths), rel_path,
                    len(combined) / sample_rate)
        return rel_path

    def concatenate_with_silence(self, file_paths: list,
                                 silence_ms: int = 300,
                                 output_path: str = "",
                                 randomize_silence: bool = True) -> str:
        """Concatenate WAV files with silence inserted between them.

        Used for multi-speaker dialogue: a clean silence gap between
        speakers sounds more natural than a crossfade (which can cause
        a volume dip and blend the two voices at the boundary).

        Args:
            file_paths: list of WAV file paths to concatenate (in order).
            silence_ms: base milliseconds of silence to insert between each
                        pair of files. Default 300ms.
            output_path: destination file path.
            randomize_silence: if True (default), the actual silence duration
                               varies randomly between 50% and 150% of
                               silence_ms for each boundary, simulating
                               natural conversation pacing. A speaker
                               continuing (same speaker as previous) gets
                               shorter pauses; a speaker switch gets longer.

        Returns:
            Path to the concatenated WAV file (relative to app root).
        """
        import numpy as np
        import random

        if not file_paths:
            return ""

        all_samples = []
        sample_rate = HIGGS_SAMPLE_RATE

        for i, path in enumerate(file_paths):
            try:
                samples, sr = self.load_wav(path)
                if i == 0:
                    sample_rate = sr
                else:
                    if sr != sample_rate:
                        logger.warning(
                            "concatenate_with_silence: sample rate mismatch "
                            "in part %d: %d vs %d", i, sr, sample_rate)
                if samples.ndim > 1:
                    samples = samples.flatten()
                all_samples.append(samples.astype(np.float32))
                # Insert silence between this part and the next (not after last).
                if i < len(file_paths) - 1:
                    if randomize_silence:
                        # Randomize: 50%–150% of base silence.
                        # This creates natural variation — some pauses
                        # are shorter (quick back-and-forth), some longer
                        # (dramatic beat). Uses a seed from the file path
                        # so the result is reproducible for the same input.
                        rng = random.Random(hash(path) & 0xFFFFFFFF)
                        factor = rng.uniform(0.5, 1.5)
                        actual_ms = int(silence_ms * factor)
                    else:
                        actual_ms = silence_ms
                    silence_samples = int(actual_ms * sample_rate / 1000)
                    if silence_samples > 0:
                        # Apply a short fade-out to the end of the current
                        # part and fade-in to the start of the next to avoid
                        # clicks at the silence boundary.
                        fade_samples = min(50, len(all_samples[-1]) // 4,
                                           silence_samples // 2)
                        if fade_samples > 0:
                            fade = np.linspace(1.0, 0.0, fade_samples,
                                               dtype=np.float32)
                            all_samples[-1][-fade_samples:] *= fade
                        all_samples.append(
                            np.zeros(silence_samples, dtype=np.float32))
                        # Fade-in will be applied to the start of the next
                        # part when it's loaded — we handle it here:
                        # (store the fade length for the next iteration)
                        # Actually, simpler: apply the fade-in to the next
                        # chunk after loading it.
            except Exception as exc:
                logger.error("Failed to load part %d for concat: %s", i, exc)

        # Apply fade-in to the start of each part after the first (which
        # follows a silence gap). This prevents clicks.
        # We do this in a second pass for simplicity.
        if randomize_silence and len(all_samples) > 2:
            for idx in range(2, len(all_samples), 2):  # every audio chunk
                chunk = all_samples[idx]
                fade_len = min(50, len(chunk) // 4)
                if fade_len > 0 and isinstance(chunk, np.ndarray):
                    fade = np.linspace(0.0, 1.0, fade_len, dtype=np.float32)
                    chunk[:fade_len] *= fade

        if not all_samples:
            return ""

        combined = np.concatenate(all_samples)

        self._write_wav(output_path, combined, sample_rate)
        rel_path = os.path.relpath(output_path, self._get_app_root())
        avg_ms = silence_ms
        logger.info("Concatenated %d parts with ~%dms randomized silence "
                    "into %s (%.1fs)",
                    len(file_paths), avg_ms, rel_path,
                    len(combined) / sample_rate)
        return rel_path

    # ------------------------------------------------------------------
    # Playback (seekable, with position tracking)
    # ------------------------------------------------------------------
    def play(self, samples, sample_rate: int = HIGGS_SAMPLE_RATE,
             start_position_sec: float = 0.0) -> None:
        """Play a waveform through the default audio output.

        Uses the sounddevice library if available; otherwise logs a warning.
        Playback supports seeking, pausing and resuming.

        Args:
            samples: float32 array in [-1.0, 1.0].
            sample_rate: sample rate in Hz.
            start_position_sec: position to start playback from (for resume
                after pause or for seeking).
        """
        import numpy as np
        arr = np.asarray(samples, dtype=np.float32).flatten()

        with self._playback_lock:
            # Stop any current playback first.
            self._stop_internal()

            self._current_playback = _PlaybackHandle()
            # Apply the master volume to the new playback.
            self._current_playback.set_volume(self._volume)
            # CRITICAL: wire the position + finished callbacks to the new
            # handle. Without this, the UI never receives playback position
            # updates or natural-finish events.
            self._current_playback.position_callback = self._position_callback
            self._current_playback.finished_callback = self._finished_callback
            try:
                self._current_playback.start(
                    arr, sample_rate, start_position_sec)
            except Exception as exc:
                logger.error("Playback failed to start: %s", exc)
                self._current_playback = None

    def pause_playback(self) -> None:
        """Pause playback. Use resume_playback() to continue."""
        with self._playback_lock:
            if self._current_playback is not None:
                self._current_playback.pause()

    def resume_playback(self) -> None:
        """Resume playback after pause."""
        with self._playback_lock:
            if self._current_playback is not None:
                self._current_playback.resume()

    def seek(self, position_sec: float) -> None:
        """Seek to a position in seconds.

        If playback is currently active, the audio jumps to the new position.
        If playback is paused, the position is updated and the user can resume
        from the new position.
        """
        with self._playback_lock:
            if self._current_playback is not None:
                self._current_playback.seek(position_sec)

    def get_playback_position(self) -> float:
        """Return the current playback position in seconds (0.0 if idle)."""
        with self._playback_lock:
            if self._current_playback is None:
                return 0.0
            return self._current_playback.position_sec

    def get_playback_duration(self) -> float:
        """Return the total duration of the current playback in seconds."""
        with self._playback_lock:
            if self._current_playback is None:
                return 0.0
            return self._current_playback.duration_sec

    def get_playback_state(self) -> str:
        """Return the current playback state.

        One of: "stopped", "playing", "paused".
        """
        with self._playback_lock:
            if self._current_playback is None:
                return "stopped"
            return self._current_playback.state

    def set_position_callback(self,
                              callback: Optional[Callable[[float, float], None]]
                              ) -> None:
        """Register a callback invoked periodically during playback.

        The callback receives (position_sec, duration_sec). It is called from
        the audio thread, so subscribers must marshal back to the UI thread.
        Pass None to clear the callback.
        """
        with self._playback_lock:
            self._position_callback = callback
            if self._current_playback is not None:
                self._current_playback.position_callback = callback

    def set_finished_callback(self,
                              callback: Optional[Callable[[], None]]) -> None:
        """Register a callback invoked when playback finishes naturally."""
        with self._playback_lock:
            self._finished_callback = callback
            if self._current_playback is not None:
                self._current_playback.finished_callback = callback

    def set_volume(self, volume: float) -> None:
        """Set the master playback volume (linear gain 0.0 - 1.0).

        Applies to the current playback (live, takes effect on the next audio
        callback) AND to all future playbacks.
        """
        with self._playback_lock:
            self._volume = max(0.0, min(1.0, float(volume)))
            if self._current_playback is not None:
                self._current_playback.set_volume(self._volume)

    def get_volume(self) -> float:
        """Return the current master volume (0.0 - 1.0)."""
        with self._playback_lock:
            return self._volume

    def stop_playback(self) -> None:
        """Stop any currently playing audio."""
        with self._playback_lock:
            self._stop_internal()

    def _stop_internal(self) -> None:
        """Stop playback (caller must hold the lock)."""
        if self._current_playback is not None:
            self._current_playback.stop()
            self._current_playback = None
            logger.info("audio_manager: Playback stopped.")

    # ------------------------------------------------------------------
    # Waveform generation (for the waveform panel preview)
    # ------------------------------------------------------------------
    def generate_waveform_peaks(self, samples, num_peaks: int = 200):
        """Downsample a waveform to a fixed number of peak values.

        Used by the waveform display panel to render the audio shape without
        plotting every sample.
        """
        import numpy as np
        arr = np.asarray(samples, dtype=np.float32)
        if len(arr) == 0:
            return np.zeros(num_peaks, dtype=np.float32)
        chunk_size = max(1, len(arr) // num_peaks)
        peaks = []
        for i in range(num_peaks):
            start = i * chunk_size
            end = start + chunk_size
            chunk = arr[start:end]
            if len(chunk) > 0:
                peaks.append(float(np.max(np.abs(chunk))))
            else:
                peaks.append(0.0)
        return peaks

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------
    def _get_app_root(self) -> str:
        """Return the application root.

        self._outputs_dir is <app_root>/outputs, so the app root is one
        directory level up.
        """
        return os.path.dirname(os.path.abspath(self._outputs_dir))


# ---------------------------------------------------------------------------
# Playback handle (seekable, with position tracking)
# ---------------------------------------------------------------------------
class _PlaybackHandle:
    """Internal handle tracking a seekable playback session.

    Uses sounddevice's OutputStream in callback mode so we can:
      - track the playback position precisely (in samples),
      - seek to any position by repositioning the read cursor,
      - pause/resume by stopping and restarting the stream,
      - report position to a UI callback at ~20 Hz.
    """

    def __init__(self):
        self._samples = None  # numpy float32 array (1-D)
        self._sample_rate: int = 0
        self._position: int = 0  # current read cursor (in samples)
        self._stream = None  # sd.OutputStream
        self._state: str = "stopped"  # "stopped", "playing", "paused"
        self._lock = threading.RLock()
        self._stop_flag = threading.Event()
        self._position_thread: Optional[threading.Thread] = None
        self.position_callback: Optional[Callable[[float, float], None]] = None
        self.finished_callback: Optional[Callable[[], None]] = None
        # Output volume (linear gain) in the range 0.0 (muted) - 1.0 (full).
        # Applied in _audio_callback so it can be changed live during playback.
        self._volume: float = 1.0

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------
    def start(self, samples, sample_rate: int,
              start_position_sec: float = 0.0) -> None:
        """Start playback from a given position."""
        import sounddevice as sd

        self._samples = samples
        self._sample_rate = sample_rate
        self._position = max(
            0, min(int(start_position_sec * sample_rate), len(samples)))
        self._state = "playing"
        self._stop_flag.clear()

        # Start the audio output stream (callback mode).
        self._stream = sd.OutputStream(
            samplerate=sample_rate,
            channels=1,
            dtype='float32',
            callback=self._audio_callback,
        )
        self._stream.start()

        # Start the position-reporter thread (~20 Hz).
        self._position_thread = threading.Thread(
            target=self._position_loop, daemon=True)
        self._position_thread.start()
        logger.info("audio_manager: Playback started (sr=%d, %.2fs)",
                    sample_rate, len(samples) / sample_rate)

    def pause(self) -> None:
        """Pause playback. Position is retained."""
        with self._lock:
            if self._state != "playing":
                return
            self._state = "paused"
        try:
            if self._stream is not None:
                self._stream.stop()
        except Exception as exc:
            logger.warning("audio_manager: stream.stop() on pause failed: %s", exc)
        logger.info("audio_manager: Playback paused at %.2fs",
                    self.position_sec)

    def resume(self) -> None:
        """Resume playback after pause."""
        with self._lock:
            if self._state != "paused":
                return
            self._state = "playing"
        try:
            if self._stream is not None:
                self._stream.start()
            else:
                # Stream was closed; restart from current position.
                import sounddevice as sd
                self._stream = sd.OutputStream(
                    samplerate=self._sample_rate,
                    channels=1,
                    dtype='float32',
                    callback=self._audio_callback,
                )
                self._stream.start()
        except Exception as exc:
            logger.warning("audio_manager: stream.start() on resume failed: %s",
                           exc)
        logger.info("audio_manager: Playback resumed at %.2fs",
                    self.position_sec)

    def seek(self, position_sec: float) -> None:
        """Seek to a position in seconds. Playback state is preserved."""
        with self._lock:
            if self._samples is None:
                return
            new_pos = max(
                0, min(int(position_sec * self._sample_rate),
                       len(self._samples)))
            self._position = new_pos
        logger.info("audio_manager: Seeked to %.2fs", position_sec)

    def stop(self) -> None:
        """Stop playback and release resources."""
        self._stop_flag.set()
        with self._lock:
            self._state = "stopped"
        try:
            if self._stream is not None:
                self._stream.stop()
                self._stream.close()
        except Exception:
            pass
        self._stream = None
        # Wait briefly for the position thread to exit.
        if self._position_thread is not None and self._position_thread.is_alive():
            self._position_thread.join(timeout=0.5)
        self._position_thread = None

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------
    @property
    def position_sec(self) -> float:
        with self._lock:
            if self._sample_rate <= 0:
                return 0.0
            return self._position / self._sample_rate

    @property
    def duration_sec(self) -> float:
        with self._lock:
            if self._sample_rate <= 0 or self._samples is None:
                return 0.0
            return len(self._samples) / self._sample_rate

    @property
    def state(self) -> str:
        with self._lock:
            return self._state

    # ------------------------------------------------------------------
    # Audio callback (called from sounddevice's audio thread)
    # ------------------------------------------------------------------
    def _audio_callback(self, outdata, frames, time_info, status):
        """Fill the output buffer from the current position."""
        with self._lock:
            if self._state != "playing" or self._samples is None:
                outdata.fill(0)
                return
            vol = self._volume  # snapshot the volume under the lock
            end = self._position + frames
            chunk = self._samples[self._position:end]
            if len(chunk) < frames:
                # End of audio: fill what we can, pad the rest with silence.
                outdata[:len(chunk), 0] = chunk * vol
                outdata[len(chunk):, 0] = 0
                self._position = len(self._samples)
                self._state = "finished"  # transient state; cleaned up below
            else:
                outdata[:, 0] = chunk * vol
                self._position = end

    # ------------------------------------------------------------------
    # Volume (live-adjustable during playback)
    # ------------------------------------------------------------------
    def set_volume(self, volume: float) -> None:
        """Set the output volume (linear gain 0.0 - 1.0).

        Thread-safe; takes effect on the next audio callback (~immediately).
        """
        with self._lock:
            self._volume = max(0.0, min(1.0, float(volume)))

    # ------------------------------------------------------------------
    # Position reporter thread (~20 Hz)
    # ------------------------------------------------------------------
    def _position_loop(self):
        """Periodically report the playback position to the UI callback."""
        last_reported = -1.0
        while not self._stop_flag.is_set():
            with self._lock:
                state = self._state
                pos = self.position_sec
                dur = self.duration_sec

            # Report position while playing.
            if state == "playing" and self.position_callback is not None:
                # Throttle: only report if position changed by >= 20ms.
                if abs(pos - last_reported) >= 0.02:
                    try:
                        self.position_callback(pos, dur)
                    except Exception as exc:
                        logger.warning(
                            "audio_manager: position_callback raised: %s", exc)
                    last_reported = pos

            # Handle natural finish.
            if state == "finished":
                if self.position_callback is not None:
                    try:
                        self.position_callback(dur, dur)
                    except Exception:
                        pass
                with self._lock:
                    self._state = "stopped"
                if self.finished_callback is not None:
                    try:
                        self.finished_callback()
                    except Exception as exc:
                        logger.warning(
                            "audio_manager: finished_callback raised: %s", exc)
                logger.info("audio_manager: Playback finished naturally.")
                break

            if state == "stopped":
                break

            self._stop_flag.wait(0.02)  # 50 Hz
