"""
SpeechStudio — Ambient Background Widget
========================================

Full-window ambient background. Uses an :class:`AmbientRenderer` to
produce a frame into a cached QPixmap. The ``paintEvent`` blits the
cached pixmap — on cache miss (first paint / resize), it generates the
pixmap inline (with a try/except safety wrapper) and blits it.

Architecture
------------
::

    AmbientBackgroundWidget (this file)
        ├── owns an AmbientRenderer (CPU or future GPU)  [injectable]
        ├── owns a cached QPixmap
        └── owns a low-frequency QTimer (animation only)

The timer advances the animation time and regenerates the pixmap at a
low frame rate. The ``paintEvent`` blits the cached pixmap on cache hit,
or generates + blits on cache miss. The renderer is never called from
multiple threads — all calls are on the UI thread.

The renderer is injected via the constructor, so the concrete
implementation can be swapped without changing this widget or the rest
of the application::

    # CPU (current):
    widget = AmbientBackgroundWidget(renderer=AmbientRendererCPU())

    # GPU (future — NOT implemented yet):
    widget = AmbientBackgroundWidget(renderer=AmbientRendererGPU())

Pixmap caching rules
--------------------
- The pixmap is regenerated when the renderer says the frame has changed
  (timer-driven, at 2 FPS) OR on cache miss (first paint / resize).
- On cache miss, the paintEvent generates the pixmap inline (with a
  try/except safety wrapper) and blits it. This ensures the gradient
  always appears, even if the timer hasn't fired yet.
- The pixmap allocation is reused when the size matches — no memory growth.
- The pixmap is invalidated on resize.

Pause / resume
--------------
The widget has two **independent** reasons to stop the timer:

1. ``set_theme_active(False)`` — the theme is opaque, no animation needed.
2. ``pause()`` — an explicit pause (e.g. during model loading).

The timer runs only when: ``theme_active`` is ``True`` **and** not
explicitly paused. Both conditions are tracked separately.

All exit paths (success, failure, cancellation) must call ``resume()``
to balance a ``pause()`` call. As a safety net, ``set_theme_active()``
also reconciles the timer state.
"""

from __future__ import annotations
from typing import Optional

from PySide6.QtCore import Qt, QTimer
from PySide6.QtGui import QPixmap, QPainter
from PySide6.QtWidgets import QWidget

from ui.panels.ambient_renderer import AmbientRenderer, AmbientRendererCPU, BG_CHARCOAL


class AmbientBackgroundWidget(QWidget):
    """Full-window ambient background with pixmap caching.

    The widget owns an :class:`AmbientRenderer` and a cached QPixmap. A
    low-frequency timer (2 FPS) advances the animation time and
    regenerates the pixmap. The ``paintEvent`` blits the cached pixmap
    on cache hit, or generates + blits on cache miss.

    See the module docstring for the full architecture description.
    """

    # Animation timer interval (ms). 500 ms = 2 FPS.
    #
    # This is intentionally conservative. The animation is very slow
    # (``time * 0.2`` movement), so 2 FPS is visually acceptable. Higher
    # frame rates (15-60 FPS) cause startup freezes and "recursive
    # repaint" warnings on some systems.
    #
    # A future GPU renderer could use a higher frame rate because GPU
    # rendering doesn't compete with the CPU for the UI thread.
    TIMER_INTERVAL_MS: int = 500

    def __init__(self, renderer: Optional[AmbientRenderer] = None,
                 parent=None):
        super().__init__(parent)
        self.setAutoFillBackground(False)
        # Do NOT intercept mouse events — let them pass through to the
        # UI widgets above this background.
        self.setAttribute(Qt.WidgetAttribute.WA_TransparentForMouseEvents, True)

        # Renderer — defaults to CPU. Can be swapped for a GPU renderer.
        self._renderer: AmbientRenderer = renderer or AmbientRendererCPU()

        # Animation state.
        self._time: float = 0.7  # start at a pleasing position

        # Cached pixmap — the paintEvent blits this. Regenerated by the
        # timer (animation) or on cache miss (first paint / resize).
        self._pixmap: Optional[QPixmap] = None
        self._pixmap_width: int = 0
        self._pixmap_height: int = 0

        # Timer state — two independent reasons to stop:
        #   _theme_active:       False when the theme is opaque.
        #   _explicitly_paused:  True when pause() was called (e.g. model load).
        # The timer runs only when: _theme_active and not _explicitly_paused.
        self._theme_active: bool = False  # start hidden; host enables via set_theme_active
        self._explicitly_paused: bool = False

        # Animation timer.
        self._timer = QTimer(self)
        self._timer.timeout.connect(self._on_tick)
        # Don't start here — the host calls set_theme_active() to start
        # the timer based on the active theme.

    # ------------------------------------------------------------------
    # Timer state management
    # ------------------------------------------------------------------
    def _update_timer_state(self) -> None:
        """Start or stop the timer based on theme + pause state.

        This is the **single source of truth** for timer state. All
        state changes (``set_theme_active``, ``pause``, ``resume``) call
        this method. Idempotent — safe to call repeatedly.
        """
        should_run = self._theme_active and not self._explicitly_paused
        if should_run and not self._timer.isActive():
            self._timer.start(self.TIMER_INTERVAL_MS)
        elif not should_run and self._timer.isActive():
            self._timer.stop()

    def set_theme_active(self, active: bool) -> None:
        """Enable or disable the ambient background based on the theme.

        Called by the host when the theme changes. When ``active`` is
        ``True`` (translucent theme), the widget is visible and the
        timer runs (unless explicitly paused). When ``False`` (opaque
        theme), the widget is hidden and the timer is stopped.

        This method does **not** affect the explicit-pause state — a
        ``pause()`` call during model loading is preserved across theme
        changes.
        """
        self._theme_active = active
        self.setVisible(active)
        self._update_timer_state()

    def pause(self) -> None:
        """Temporarily pause the animation (e.g. during model loading).

        The animation stays paused until :meth:`resume` is called.
        Every ``pause()`` must be balanced by a ``resume()`` on all
        code paths (success, failure, cancellation).
        """
        self._explicitly_paused = True
        self._update_timer_state()

    def resume(self) -> None:
        """Resume the animation after an explicit :meth:`pause`.

        Safe to call even if not paused — clears the flag and
        reconciles the timer state. Idempotent.
        """
        self._explicitly_paused = False
        self._update_timer_state()

    def is_running(self) -> bool:
        """Return ``True`` if the animation timer is currently running."""
        return self._timer.isActive()

    def stop(self) -> None:
        """Permanently stop the animation (called on application shutdown)."""
        self._timer.stop()

    # ------------------------------------------------------------------
    # Animation tick
    # ------------------------------------------------------------------
    def _on_tick(self) -> None:
        """Timer tick — advance time and regenerate the pixmap.

        The timer fires at 2 FPS (500 ms). Each tick advances the
        animation time and regenerates the pixmap. The paintEvent will
        blit the updated pixmap on the next repaint.
        """
        self._time += self.TIMER_INTERVAL_MS / 1000.0
        self._regenerate_pixmap()
        self.update()  # schedule a repaint (paintEvent will blit)

    # ------------------------------------------------------------------
    # Pixmap caching
    # ------------------------------------------------------------------
    def _ensure_pixmap(self, width: int, height: int) -> None:
        """Ensure ``self._pixmap`` exists at the given size.

        Reuses the existing pixmap if the size matches (no
        reallocation). Only allocates a new pixmap when the size
        changes — this prevents memory growth from repeated allocations
        during resize sequences.
        """
        if (self._pixmap is not None
                and self._pixmap_width == width
                and self._pixmap_height == height
                and not self._pixmap.isNull()):
            return  # cache is valid

        # Allocate a new pixmap at the requested size. The old QPixmap
        # is garbage-collected by Python/Qt when its reference count
        # drops to zero — no memory leak.
        self._pixmap = QPixmap(width, height)
        self._pixmap_width = width
        self._pixmap_height = height

    def _regenerate_pixmap(self) -> bool:
        """Render the current frame into ``self._pixmap`` using the renderer.

        Returns ``True`` if rendering succeeded, ``False`` on failure.
        On failure, the pixmap is left in its previous state (or None).

        Called by:
          - :meth:`_on_tick` (timer, at 2 FPS)
          - :meth:`paintEvent` (on cache miss, with try/except safety)

        Reuses the pixmap allocation if the size matches.
        """
        w = max(1, self.width())
        h = max(1, self.height())

        self._ensure_pixmap(w, h)

        if self._pixmap is None or self._pixmap.isNull():
            return False

        try:
            success = self._renderer.render(self._time, w, h, self._pixmap)
            return success
        except Exception:
            # If the renderer fails (e.g. allocation error), leave the
            # pixmap in its previous state. The paintEvent will fall back
            # to a charcoal fill.
            return False

    def _is_cache_valid(self) -> bool:
        """Return ``True`` if the cached pixmap matches the current widget size."""
        return (self._pixmap is not None
                and not self._pixmap.isNull()
                and self._pixmap_width == self.width()
                and self._pixmap_height == self.height())

    # ------------------------------------------------------------------
    # Paint / resize
    # ------------------------------------------------------------------
    def paintEvent(self, event) -> None:
        """Blit the cached pixmap, or generate + blit on cache miss.

        On cache miss (first paint or resize), this method generates the
        pixmap inline (with a try/except safety wrapper) and blits it.
        This ensures the gradient always appears, even if the timer
        hasn't fired yet.

        The generation is wrapped in try/except so that any rendering
        error falls back to a charcoal fill instead of crashing the app.
        """
        painter = QPainter(self)

        if self._is_cache_valid():
            # Cache hit — blit the cached pixmap (very fast).
            painter.drawPixmap(0, 0, self._pixmap)
        else:
            # Cache miss — try to generate the pixmap inline.
            # This is wrapped in try/except so that any rendering error
            # (e.g. allocation failure, renderer exception) falls back to
            # a charcoal fill instead of crashing the app.
            if self._regenerate_pixmap() and self._pixmap is not None and not self._pixmap.isNull():
                painter.drawPixmap(0, 0, self._pixmap)
            else:
                # Fallback: solid charcoal fill.
                painter.fillRect(self.rect(), BG_CHARCOAL)

        painter.end()

    def resizeEvent(self, event) -> None:
        """On resize, invalidate the cached pixmap.

        The next ``paintEvent`` will regenerate at the new size (inline,
        with try/except safety).
        """
        self._pixmap = None
        self._pixmap_width = 0
        self._pixmap_height = 0
        # Don't call update() here — Qt will schedule a paintEvent
        # automatically after the resize.
        super().resizeEvent(event)
